# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/agent.proto\x12\x05\x61gent\"\x1e\n\x0b\x43hatRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x43hatResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"/\n\rActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06params\x18\x02 \x01(\t\"1\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t2\x7f\n\x0c\x41gentService\x12\x31\n\x04\x43hat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse0\x01\x12<\n\rExecuteAction\x12\x14.agent.ActionRequest\x1a\x15.agent.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=28
  _globals['_CHATREQUEST']._serialized_end=58
  _globals['_CHATRESPONSE']._serialized_start=60
  _globals['_CHATRESPONSE']._serialized_end=91
  _globals['_ACTIONREQUEST']._serialized_start=93
  _globals['_ACTIONREQUEST']._serialized_end=140
  _globals['_ACTIONRESPONSE']._serialized_start=142
  _globals['_ACTIONRESPONSE']._serialized_end=191
  _globals['_AGENTSERVICE']._serialized_start=193
  _globals['_AGENTSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
